-- ============================================================
-- Full schema – run once against an empty database.
-- Safe to re-run: every statement uses IF NOT EXISTS.
-- ============================================================

-- Required extensions
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ------------------------------------------------------------
-- users
-- One row per unique frontend username.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  username   TEXT        NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ------------------------------------------------------------
-- sessions
-- One row per conversation.  id = UUID generated by the
-- frontend (crypto.randomUUID()) so the client is authoritative
-- for session identity.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sessions (
  id         UUID        PRIMARY KEY,
  user_id    UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS sessions_user_id_idx ON sessions(user_id);

-- ------------------------------------------------------------
-- messages
-- Ordered chat turns stored per session.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS messages (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id UUID        NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  role       TEXT        NOT NULL CHECK (role IN ('user', 'assistant')),
  content    TEXT        NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS messages_session_id_idx ON messages(session_id);

-- ------------------------------------------------------------
-- citations
-- Sources surfaced by the RAG agent for a specific assistant
-- message.  citation_index matches the [N] inline references.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS citations (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  message_id       UUID        NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
  session_id       UUID        NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  citation_index   INT         NOT NULL,
  source_title     TEXT        NOT NULL,
  url              TEXT,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS citations_message_id_idx ON citations(message_id);
CREATE INDEX IF NOT EXISTS citations_session_id_idx ON citations(session_id);

-- ------------------------------------------------------------
-- chunks
-- RAG knowledge base: parent-child hybrid retrieval.
-- id format: "{userId}:{pageId}:{revisionId}:{chunkIdx}"
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS chunks (
  id                    TEXT        PRIMARY KEY,
  user_id               TEXT        NOT NULL,
  page_id               INTEGER     NOT NULL,
  revision_id           INTEGER     NOT NULL,
  article_title         TEXT        NOT NULL,
  document_introduction TEXT        NOT NULL,
  section_title         TEXT        NOT NULL,
  content               TEXT        NOT NULL,
  metadata              JSONB       NOT NULL,
  embedding             vector(384),
  fts_index tsvector GENERATED ALWAYS AS (
    setweight(to_tsvector('english', coalesce(article_title, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(document_introduction, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(content, '')), 'C')
  ) STORED
);

CREATE INDEX IF NOT EXISTS chunks_user_page_idx ON chunks (user_id, page_id);
CREATE INDEX IF NOT EXISTS fts_search_idx       ON chunks USING GIN  (fts_index);
CREATE INDEX IF NOT EXISTS vector_search_idx    ON chunks USING hnsw (embedding vector_cosine_ops);