import {
  Controller,
  Post,
  Get,
  Query,
  Res,
  Body,
  Inject,
  BadRequestException,
} from '@nestjs/common';
import type { FastifyReply } from 'fastify';
import { Pool } from 'pg';
import { EmbeddingService } from 'src/embedding/embedding.service';
import { ChatRepository } from 'src/db/chat.repository';
import { RagAgent } from './rag.agent';

@Controller('')
export class AiController {
  constructor(
    private embedder: EmbeddingService,
    private chatRepo: ChatRepository,
    @Inject('PG_POOL') private pool: Pool,
  ) {}

  /**
   * POST /chat
   * Body: {
   *   message:    string                           – the latest user message
   *   messages?:  { role, content }[]              – full conversation from the client
   *   sessionId:  string                           – UUID generated by the frontend
   *   username?:  string                           – optional display name
   * }
   */
  @Post('chat')
  async chat(
    @Body()
    body: {
      message: string;
      messages?: { role: string; content: string }[];
      sessionId: string;
      username?: string;
    },
    @Res() res: FastifyReply,
  ) {
    if (!body?.sessionId?.trim()) {
      throw new BadRequestException('sessionId is required');
    }
    const userContent = typeof body?.message === 'string' ? body.message.trim() : '';
    if (!userContent) {
      throw new BadRequestException('message is required');
    }

    const username = body.username?.trim() || 'anonymous';
    const sessionId = body.sessionId.trim();
    const ragUserId = process.env.RAG_USER_ID ?? 'cli-system';

    const userId_db = await this.chatRepo.upsertUser(username);
    await this.chatRepo.upsertSession(sessionId, userId_db);
    await this.chatRepo.saveMessage(sessionId, 'user', userContent);

    // Use the full conversation history from the frontend if available (guaranteed
    // to be complete), otherwise fall back to the DB for the last 10 turns.
    const contextMessages =
      body.messages && body.messages.length > 0
        ? body.messages
        : await this.chatRepo.getLastMessages(sessionId, 10);

    const agent = new RagAgent(this.pool, this.embedder);
    const { textStream, getSources, generateStructuredCitations } =
      await agent.chat(ragUserId, contextMessages);

    res.raw.writeHead(200, {
      'Content-Type': 'text/plain; charset=utf-8',
      'Transfer-Encoding': 'chunked',
    });

    let fullText = '';
    try {
      for await (const chunk of textStream) {
        res.raw.write(chunk);
        fullText += chunk;
      }

      const sources = getSources();
      if (sources.length) {
        const refs = sources
          .map((s, i) => `[${i + 1}] [${s.title}](${s.url})`)
          .join('\n');
        res.raw.write(`\n\n---\n**Sources:**\n${refs}`);

        // Structured citations block (generateObject + CitationSchema).
        const structured = await generateStructuredCitations(fullText);
        res.raw.write(
          `\n\n<!--CITATIONS_JSON:${JSON.stringify(structured)}-->`,
        );
      }

      const assistantMsgId = await this.chatRepo.saveMessage(
        sessionId,
        'assistant',
        fullText,
      );
      if (sources.length) {
        await this.chatRepo.saveCitations(assistantMsgId, sessionId, sources);
      }
    } catch (err) {
      console.error('[Stream error]', err);
      res.raw.write('\n\n[Error: response stream interrupted]');
    } finally {
      res.raw.end();
    }
  }

  /**
   * GET /debug?userId=cli-system
   * Returns document count and sample titles for a userId.
   */
  @Get('debug')
  async debug(@Query('userId') userId: string) {
    if (!userId) return { error: 'userId query param is required' };

    const countRes = await this.pool.query<{ count: string }>(
      'SELECT COUNT(*) AS count FROM chunks WHERE user_id = $1',
      [userId],
    );
    const sampleRes = await this.pool.query<{ title: string }>(
      `SELECT DISTINCT article_title AS title FROM chunks WHERE user_id = $1 LIMIT 5`,
      [userId],
    );

    return {
      userId,
      chunkCount: parseInt(countRes.rows[0].count, 10),
      sampleTitles: sampleRes.rows.map((r) => r.title),
    };
  }
}
